### ISSUE TITLE
muss "do" command for arbitrary tasks?

### ISSUE THREAD

**Issue by rwstauner** [instructure-bridge/muss#14]
```
do_commands:
  docs: muss run something-to-generate docs
  pg_dump: muss run postgres env PGDATABASE=cluster3 pg_dump -h postgres -U postgres > tmp/muss.dumpall.sql
  pg_restore: muss exec postgres psql -h localhost -U get_smart -d postgres -f - < tmp/muss.dumpall.sql
```

Not sure about the command syntax though... do we put `muss run` in front of everything for maximum flexibility?  or assume that commands would be run in a given container?
Then the `do` commands would be discoverable through `muss help`.
